### PR TITLE
Updates for bibliography changes in upcoming v0.3.0 vitae release

### PR DESCRIPTION
**Pull request by mitchelloharawild**
{vitae} v0.3.0 will be submitted to CRAN soon. I've used your CV as a test case for identifying the migration work necessary for v0.2.2 -> v0.3.0, and to check if previous functionality could be preserved.

This PR makes necessary changes to the bibliography entries for the use of pandoc + CSL instead of biblatex.
You may want to work a bit more on the CSL file, however I can confirm that hanging indents are working appropriately now with pandoc v2.11.

### CODE REVIEW

**Comment by robjhyndman** [comment]
Were you able to compile? I'm getting problems with filtering on `issued`:

```r
> bibliography_entries("rjhpubs.bib") %>%
+   filter(type == "book", issued > 2015) %>%
+   arrange(issued, author$family)
Error: Problem with `filter()` input `..2`.
x Can't combine `..1` <csl_date> and `..2` <double>.
ℹ Input `..2` is `issued > 2015`.
```

**Comment by mitchelloharawild** [comment]
I was able to compile, but I can imagine how this error would occur. I think this can/should be fixed in `{vitae}`.

**Comment by mitchelloharawild** [comment]
For me `issued` is an integer, are you using the latest `{vitae}` dev version?

**Comment by mitchelloharawild** [comment]
``` r
library(vitae)
#> 
#> Attaching package: 'vitae'
#> The following object is masked from 'package:stats':
#> 
#>     filter
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
bibliography_entries("~/github/CV-1/rjhpubs.bib") %>%
  filter(type == "book", issued > 2015) %>%
  arrange(issued, author$family) %>% 
  as_tibble()
#> # A tibble: 1 x 22
#>   author     id    issued title url   `container-titl… note  type  genre number
#>   <csl name> <chr>  <int> <chr> <chr> <chr>            <chr> <chr> <chr> <chr> 
#> 1 Rob J Hyn… fpp2    2018 Fore… OTex… <NA>             <NA>  book  <NA>  <NA>  
#> # … with 12 more variables: publisher <chr>, editor <list>,
#> #   `title-short` <chr>, `collection-title` <chr>, page <chr>,
#> #   `publisher-place` <chr>, volume <chr>, issue <chr>, `chapter-number` <dbl>,
#> #   doi <chr>, edition <chr>, `collection-number` <chr>
```

<sup>Created on 2020-11-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
<details>
<summary>
Session info
</summary>

``` r
devtools::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 4.0.2 (2020-06-22)
#>  os       Ubuntu 20.04.1 LTS          
#>  system   x86_64, linux-gnu           
#>  ui       X11                         
#>  language en_AU:en                    
#>  collate  en_AU.UTF-8                 
#>  ctype    en_AU.UTF-8                 
#>  tz       Australia/Melbourne         
#>  date     2020-11-06                  
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version    date       lib source        
#>  assertthat    0.2.1      2019-03-21 [1] CRAN (R 4.0.2)
#>  backports     1.1.10     2020-09-15 [1] CRAN (R 4.0.2)
#>  callr         3.5.1      2020-10-13 [1] CRAN (R 4.0.2)
#>  cli           2.1.0      2020-10-12 [1] CRAN (R 4.0.2)
#>  crayon        1.3.4      2017-09-16 [1] CRAN (R 4.0.2)
#>  desc          1.2.0      2018-05-01 [1] CRAN (R 4.0.2)
#>  devtools      2.3.2      2020-09-18 [1] CRAN (R 4.0.2)
#>  digest        0.6.27     2020-10-24 [1] CRAN (R 4.0.2)
#>  dplyr       * 1.0.2      2020-08-18 [1] CRAN (R 4.0.2)
#>  ellipsis      0.3.1      2020-05-15 [1] CRAN (R 4.0.2)
#>  evaluate      0.14       2019-05-28 [1] CRAN (R 4.0.2)
#>  fansi         0.4.1      2020-01-08 [1] CRAN (R 4.0.2)
#>  fs            1.5.0      2020-07-31 [1] CRAN (R 4.0.2)
#>  generics      0.0.2      2018-11-29 [1] CRAN (R 4.0.2)
#>  glue          1.4.2      2020-08-27 [1] CRAN (R 4.0.2)
#>  highr         0.8        2019-03-20 [1] CRAN (R 4.0.2)
#>  htmltools     0.5.0      2020-06-16 [1] CRAN (R 4.0.2)
#>  knitr         1.30       2020-09-22 [1] CRAN (R 4.0.2)
#>  lifecycle     0.2.0      2020-03-06 [1] CRAN (R 4.0.2)
#>  magrittr      1.5        2014-11-22 [1] CRAN (R 4.0.2)
#>  memoise       1.1.0      2017-04-21 [1] CRAN (R 4.0.2)
#>  pillar        1.4.6      2020-07-10 [1] CRAN (R 4.0.2)
#>  pkgbuild      1.1.0      2020-07-13 [1] CRAN (R 4.0.2)
#>  pkgconfig     2.0.3      2019-09-22 [1] CRAN (R 4.0.2)
#>  pkgload       1.1.0      2020-05-29 [1] CRAN (R 4.0.2)
#>  prettyunits   1.1.1      2020-01-24 [1] CRAN (R 4.0.2)
#>  processx      3.4.4      2020-09-03 [1] CRAN (R 4.0.2)
#>  ps            1.4.0      2020-10-07 [1] CRAN (R 4.0.2)
#>  purrr         0.3.4      2020-04-17 [1] CRAN (R 4.0.2)
#>  R6            2.4.1      2019-11-12 [1] CRAN (R 4.0.2)
#>  remotes       2.2.0      2020-07-21 [1] CRAN (R 4.0.2)
#>  rlang         0.4.8      2020-10-08 [1] CRAN (R 4.0.2)
#>  rmarkdown     2.5        2020-10-21 [1] CRAN (R 4.0.2)
#>  rprojroot     1.3-2      2018-01-03 [1] CRAN (R 4.0.2)
#>  sessioninfo   1.1.1      2018-11-05 [1] CRAN (R 4.0.2)
#>  stringi       1.5.3      2020-09-09 [1] CRAN (R 4.0.2)
#>  stringr       1.4.0      2019-02-10 [1] CRAN (R 4.0.2)
#>  testthat      2.3.2      2020-03-02 [1] CRAN (R 4.0.2)
#>  tibble        3.0.4      2020-10-12 [1] CRAN (R 4.0.2)
#>  tidyselect    1.1.0      2020-05-11 [1] CRAN (R 4.0.2)
#>  usethis       1.6.3      2020-09-17 [1] CRAN (R 4.0.2)
#>  utf8          1.1.4      2018-05-24 [1] CRAN (R 4.0.2)
#>  vctrs         0.3.4      2020-08-29 [1] CRAN (R 4.0.2)
#>  vitae       * 0.2.2.9000 2020-11-06 [1] local         
#>  withr         2.3.0      2020-09-22 [1] CRAN (R 4.0.2)
#>  xfun          0.18       2020-09-29 [1] CRAN (R 4.0.2)
#>  yaml          2.2.1      2020-02-01 [1] CRAN (R 4.0.2)
#> 
#> [1] /home/mitchell/R/x86_64-pc-linux-gnu-library/4.0
#> [2] /opt/R/4.0.0/lib/R/library
```

</details>

**Comment by robjhyndman** [comment]
I forgot to update my pandoc version. Now working.

**Comment by mitchelloharawild** [comment]
Good to know. I'll need to add better support for older pandoc versions in that case.

**Pull request merged**
